services:
  app:
    build: .
    image: ghcr.io/m0wer/mercaapi:master
    ports:
      - "8000:80"
    volumes:
      - ./app:/app/app
      - ./mercadona.db:/app/mercadona.db
      - ./main.py:/app/main.py
      - ./alembic.ini:/app/alembic.ini
